/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContattoRouteImport } from './routes/contatto'
import { Route as LicensingRouteImport } from './routes/licensing'
import { Route as PersonalizzaRouteImport } from './routes/personalizza'
import { Route as ProgettiRouteImport } from './routes/progetti'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattoRoute = ContattoRouteImport.update({
  id: '/contatto',
  path: '/contatto',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensingRoute = LicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizzaRoute = PersonalizzaRouteImport.update({
  id: '/personalizza',
  path: '/personalizza',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgettiRoute = ProgettiRouteImport.update({
  id: '/progetti',
  path: '/progetti',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogoRoute,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contatto': typeof ContattoRoute
  '/licensing': typeof LicensingRoute
  '/personalizza': typeof PersonalizzaRoute
  '/progetti': typeof ProgettiRoute
  '/termini': typeof TerminiRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/contatto': typeof ContattoRoute
  '/licensing': typeof LicensingRoute
  '/personalizza': typeof PersonalizzaRoute
  '/progetti': typeof ProgettiRoute
  '/termini': typeof TerminiRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/catalogo': typeof CatalogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contatto': typeof ContattoRoute
  '/licensing': typeof LicensingRoute
  '/personalizza': typeof PersonalizzaRoute
  '/progetti': typeof ProgettiRoute
  '/termini': typeof TerminiRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/catalogo'
    | '/contatto'
    | '/licensing'
    | '/personalizza'
    | '/progetti'
    | '/termini'
    | '/catalogo/$slug'
    | '/catalogo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/contatto'
    | '/licensing'
    | '/personalizza'
    | '/progetti'
    | '/termini'
    | '/catalogo/$slug'
    | '/catalogo'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/catalogo'
    | '/contatto'
    | '/licensing'
    | '/personalizza'
    | '/progetti'
    | '/termini'
    | '/catalogo/$slug'
    | '/catalogo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  ContattoRoute: typeof ContattoRoute
  LicensingRoute: typeof LicensingRoute
  PersonalizzaRoute: typeof PersonalizzaRoute
  ProgettiRoute: typeof ProgettiRoute
  TerminiRoute: typeof TerminiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatto': {
      id: '/contatto'
      path: '/contatto'
      fullPath: '/contatto'
      preLoaderRoute: typeof ContattoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licensing': {
      id: '/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof LicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizza': {
      id: '/personalizza'
      path: '/personalizza'
      fullPath: '/personalizza'
      preLoaderRoute: typeof PersonalizzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progetti': {
      id: '/progetti'
      path: '/progetti'
      fullPath: '/progetti'
      preLoaderRoute: typeof ProgettiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof CatalogoRoute
    }
  }
}

interface CatalogoRouteChildren {
  CatalogoSlugRoute: typeof CatalogoSlugRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoSlugRoute: CatalogoSlugRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  ContattoRoute: ContattoRoute,
  LicensingRoute: LicensingRoute,
  PersonalizzaRoute: PersonalizzaRoute,
  ProgettiRoute: ProgettiRoute,
  TerminiRoute: TerminiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
